import Head from 'next/head'
import { MutableRefObject, useEffect, useRef } from 'react'
import { Game } from '../models/Game'
import styles from "@/styles/Homepage.module.css"
import { gameSettings } from '..'

export default function Home() {

    const canvasRef = useRef() as MutableRefObject<HTMLCanvasElement>
    useEffect(() => {
        const canvas = canvasRef.current
        const ctx = canvas.getContext("2d")
        gameSettings.canvas = canvas
        gameSettings.ctx = ctx


        let game = new Game()
        const audio = new Audio("/sounds/bck.mp3")
        audio.volume = .05
        audio.loop = true


        const animate = () => {
            requestAnimationFrame(animate)
            // 16 = width
            //  9 = height
            canvas.height = innerHeight * .9
            canvas.width = canvas.height * 9 / 16

            if (!game.gameStarted) {
                ctx!.save()
                ctx!.fillRect(0, 0, canvas.width, canvas.height)
                ctx!.fillStyle = "white"
                ctx!.textAlign = "center"
                ctx!.font = "20px Sans-Serif"
                ctx!.fillText(
                    "PRESS ENTER TO START",
                    gameSettings.canvas!.width / 2,
                    gameSettings.canvas!.height / 2
                )
                ctx!.restore()
                if (game.input.keys.includes("Enter"))
                    game.gameStarted = true
                return;
            }
            audio.play()

            game.update()
            game.draw()

            if (game.gameEnded) {
                const HigherScore = localStorage.getItem("score") || 0
                if (gameSettings.score > HigherScore)
                    localStorage.setItem("score", gameSettings.score)
            }

            if (game.input.keys.includes("KeyR")) {
                game = new Game()
                game.gameStarted = true
                gameSettings.score = 0
            }
        }

        animate()
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <canvas className={styles.canvas} ref={canvasRef}></canvas>
            </main>
        </>
    )
}
